In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not avalable. You are using CPU")

GPU is available!
Using GPU: Tesla T4


# Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3)

## Empty function is just allocate the memory

In [5]:
# check type
type(a)


torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.7357, 0.8277, 0.9486],
        [0.2571, 0.4194, 0.3782]])

In [9]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

## when we use manual_seed with rand it generate same random numbers evrytime


In [11]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(3))

# using full
print("using full ->", torch.full((3,3), 5))


using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [19]:
# fing data type
x.dtype

torch.int64

In [20]:
# assign data type
torch.tensor([1.0,2.3,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [22]:
# Using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathmatical Operation

## 1. Scalar operation

In [23]:
x = torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [24]:
# addition
x + 2

# Substraction
x - 2

# Multiplication
x * 3

# Division
x / 3

# int divsion
(x * 100)//3

# mod
((x * 100)//3)%2

# power
x**2

tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

## 2. Element wise operation

### when you have 2 ror more than 2 tensor so we do element wise operation on them

In [25]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [26]:
# add
a + b

# Subtraction
a - b

# Multiplcation
a * b

# Division
a / b

# Floor Division
a // b

# Modulus
a % b

# Exponent
a ** b

# Power
a ** b

# mod

a % b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [27]:
c = torch.tensor([1, -2, 3, -4])

In [28]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [29]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [30]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [31]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [32]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [33]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [34]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction Operation

In [36]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[3., 9., 4.],
        [0., 5., 7.]])

In [37]:
# sum
torch.sum(e)

tensor(28.)

In [38]:
# Sum along column
torch.sum(e, dim=0)

tensor([ 3., 14., 11.])

In [39]:
# Sum alng column
torch.sum(e, dim=1)

tensor([16., 12.])

In [40]:
# mean
torch.mean(e)

tensor(4.6667)

In [41]:
# mean along column
torch.mean(e, dim=0)

tensor([1.5000, 7.0000, 5.5000])

In [42]:
# median
torch.median(e)

tensor(4.)

In [43]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [46]:
# product
torch.prod(e)

tensor(0.)

In [47]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [48]:
# variance
torch.var(e)

tensor(9.8667)

In [49]:
# argmax
torch.argmax(e)

tensor(1)

In [51]:
# argmin
torch.argmin(e)

tensor(3)

## 4. Matrix Operation

In [52]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 9, 9],
        [7, 5, 9]])
tensor([[8, 9],
        [7, 9],
        [2, 6]])


In [53]:
# matrix Multiplication
torch.matmul(f, g)

tensor([[121, 180],
        [109, 162]])

In [54]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [55]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 7],
        [9, 5],
        [9, 9]])

In [56]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[7., 7., 8.],
        [3., 6., 1.],
        [5., 5., 0.]])

In [57]:
# determinant
torch.det(h)

tensor(-120.)

In [58]:
# inverse
torch.inverse(h)

tensor([[ 4.1667e-02, -3.3333e-01,  3.4167e-01],
        [-4.1667e-02,  3.3333e-01, -1.4167e-01],
        [ 1.2500e-01, -6.9539e-09, -1.7500e-01]])

## 5. Comparison Operation

In [61]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[6, 2, 9],
        [5, 0, 4]])
tensor([[2, 7, 1],
        [1, 5, 4]])


In [62]:
# Greater than
i > j

tensor([[ True, False,  True],
        [ True, False, False]])

In [63]:
# smaller than
i < j

tensor([[False,  True, False],
        [False,  True, False]])

In [64]:
# equal to
i == j

tensor([[False, False, False],
        [False, False,  True]])

In [65]:
# not equal to
i != j

tensor([[ True,  True,  True],
        [ True,  True, False]])

In [66]:
# Grater than equal to
i >= j

tensor([[ True, False,  True],
        [ True, False,  True]])

In [67]:
# Smaller than equal to
i <= j

tensor([[False,  True, False],
        [False,  True,  True]])

## 6. Special function

In [69]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 5., 6.],
        [1., 4., 5.]])

In [70]:
# log
torch.log(k)

tensor([[0.6931, 1.6094, 1.7918],
        [0.0000, 1.3863, 1.6094]])

In [71]:
# exp
torch.exp(k)

tensor([[  7.3891, 148.4132, 403.4288],
        [  2.7183,  54.5981, 148.4132]])

In [72]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 2.2361, 2.4495],
        [1.0000, 2.0000, 2.2361]])

In [73]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9933, 0.9975],
        [0.7311, 0.9820, 0.9933]])

In [74]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.7311, 0.7311, 0.7311],
        [0.2689, 0.2689, 0.2689]])

In [75]:
# relu
torch.relu(k)

tensor([[2., 5., 6.],
        [1., 4., 5.]])

## Inplace Operation

In [78]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9157, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])
tensor([[0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847]])


In [79]:
m.add_(n)

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [80]:
m

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [81]:
n

tensor([[0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847]])

In [82]:
torch.relu(m)

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [83]:
m.relu_()

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [84]:
m

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

# Copying a Tensor

In [86]:
o = torch.rand(2,3)
o

tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

In [87]:
p = o

In [88]:
p

tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

In [89]:
o[0][0] = 0

In [90]:
0

0

In [91]:
p

tensor([[0.0000, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

In [92]:
id(o)

137940716794048

In [93]:
id(p)

137940716794048

In [94]:
p = o.clone()

In [95]:
o

tensor([[0.0000, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

In [96]:
p

tensor([[0.0000, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

In [97]:
a[0][0] = 10

In [98]:
o

tensor([[0.0000, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

In [99]:
p

tensor([[0.0000, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

In [100]:
id(o)

137940716794048

In [101]:
id(p)

137940716264320