# PyTorch Dataset and DataLoader

In this notebook, we will learn how to:

1. Create a synthetic classification dataset using Scikit-learn.
2. Convert NumPy arrays into PyTorch tensors.
3. Understand the `Dataset` class in PyTorch.
4. Create a custom Dataset.
5. Understand `__init__()`, `__len__()`, and `__getitem__()`.
6. Access individual samples from a Dataset.
7. Understand the `DataLoader` class.
8. Create batches from a Dataset.
9. Understand `batch_size` and `shuffle`.
10. Iterate through batches during model training.

These concepts form an important part of the PyTorch training pipeline.

### Basic PyTorch Training Pipeline

```text
Raw Data
   ↓
Dataset
   ↓
DataLoader
   ↓
Batches
   ↓
Neural Network
   ↓
Loss
   ↓
Backpropagation
   ↓
Optimizer

In [ ]:
from sklearn.datasets import make_classification
import torch

# Creating a Synthetic Dataset

We can use Scikit-learn's `make_classification()` function to generate
a small artificial classification dataset.

### Syntax

```python
make_classification(
    n_samples,
    n_features,
    n_informative,
    n_redundant,
    n_classes,
    random_state
)

| Parameter       | Meaning                                                                        |
| --------------- | ------------------------------------------------------------------------------ |
| `n_samples`     | Number of data points/samples                                                  |
| `n_features`    | Total number of input features                                                 |
| `n_informative` | Number of features that actually contain useful information for classification |
| `n_redundant`   | Number of redundant features created from informative features                 |
| `n_classes`     | Number of target classes                                                       |
| `random_state`  | Makes the generated dataset reproducible                                       |


In [ ]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [ ]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [ ]:
X.shape

(10, 2)

In [ ]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

### Understanding `X.shape`

`X.shape` tells us the dimensions of the feature matrix.

Since we created:

- 10 samples
- 2 features

the shape will be:

```text
(10, 2)

### Understanding `y`

`y` contains the target labels for each sample.

Since there are 10 samples:

```text
y.shape → (10,)

In [ ]:
y.shape

(10,)


---


# Converting NumPy Arrays to PyTorch Tensors

PyTorch models work with PyTorch tensors.

Our `X` and `y` are currently NumPy arrays, so we convert them into tensors.

### Why different data types?

For features:

```python
dtype=torch.float32

In [ ]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [ ]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [ ]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

#  What is a Dataset?

A **Dataset** is an object that stores and provides access to our data.

In PyTorch, the Dataset abstraction allows us to:

- Store features and labels.
- Find the total number of samples.
- Retrieve an individual sample.
- Keep data handling separate from the model.

PyTorch provides:

```python
torch.utils.data.Dataset

In [ ]:
from torch.utils.data import Dataset, DataLoader

# Creating a Custom Dataset

We create our own Dataset class by inheriting from PyTorch's `Dataset`.

### Syntax

```python
class CustomDataset(Dataset):

In [ ]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

# Creating a Custom Dataset

We create our own Dataset class by inheriting from PyTorch's `Dataset`.

### Syntax

```python
class CustomDataset(Dataset):

CustomDataset → Our own Dataset class
Dataset       → PyTorch's base Dataset class

#  Understanding `__init__()`

```python
def __init__(self, features, labels):

In [ ]:
dataset = CustomDataset(X, y)

In [ ]:
len(dataset)

10

#  Understanding `__getitem__()`

```python
def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [ ]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

#  What is a DataLoader?

A `DataLoader` is responsible for loading data from a Dataset in a convenient
way, especially during model training.

PyTorch provides:

```python
torch.utils.data.DataLoader



#  Creating a DataLoader

### Syntax

```python
DataLoader(
    dataset,
    batch_size=...,
    shuffle=...
)

In [ ]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=False)

#  Iterating Through the DataLoader

We can use a `for` loop to retrieve batches from the DataLoader.

```python
for batch_features, batch_labels in dataloader:

In [ ]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------


# Complete Data Flow

Our complete pipeline is:

```text
make_classification()
        ↓
   NumPy arrays
        ↓
   X and y
        ↓
torch.tensor()
        ↓
PyTorch tensors
        ↓
CustomDataset
        ↓
Dataset object
        ↓
DataLoader
        ↓
Batches
        ↓
Neural Network

#  Dataset vs DataLoader

| Dataset | DataLoader |
|---|---|
| Stores/provides access to data | Loads data from Dataset |
| Works mainly with individual samples | Works mainly with batches |
| Implements `__len__()` | Uses Dataset length |
| Implements `__getitem__()` | Calls `__getitem__()` to obtain samples |
| Defines how data is accessed | Defines how data is batched/iterated |
| Example: `dataset[2]` | Example: `for batch in dataloader` |

### Easy way to remember

**Dataset = Where/how to get one sample**

**DataLoader = How to deliver samples to the model**





#  Important Definitions — Quick Revision

### Dataset

A PyTorch Dataset is an abstraction that provides access to individual
samples and their corresponding labels.

### Custom Dataset

A user-defined Dataset class created by inheriting from PyTorch's
`Dataset` class.

### `__init__()`

Initializes the Dataset and stores the required data.

### `__len__()`

Returns the total number of samples in the Dataset.

### `__getitem__()`

Returns one sample and its corresponding label using an index.

### DataLoader

A PyTorch utility that loads data from a Dataset and organizes it into
batches for efficient processing.

### Batch

A small group of samples processed together by the model.

### Batch Size

The number of samples contained in one batch.

### Shuffle

Determines whether the order of samples is randomized before batching.

#  Why Dataset and DataLoader Are Important

When training a neural network on a small dataset, we could technically
pass the entire dataset directly to the model.

However, real-world datasets can contain:

- Thousands of images
- Millions of text samples
- Large numerical datasets
- Large audio/video datasets

Loading everything at once may consume too much memory.

Dataset + DataLoader solve this problem by allowing us to:

- Load data in batches.
- Control batch size.
- Shuffle training data.
- Process large datasets efficiently.
- Separate data preparation from model architecture.

This becomes especially important when working with:

- CNNs
- RNNs
- Transformers
- Computer Vision datasets
- NLP datasets
- Large-scale Deep Learning projects